### PR TITLE
Fix memory leak in sample code.

### PR DESCRIPTION
**Pull request by COx2**
I found a memory leak in the Sample code and propose to fix it.
I have identified two cases of memory leaks, and this is one of them. I will submit another proposal to fix the other one if it is identified.

NOTE: I have not build and tested on all platforms. In particular, Objectve-C is one that I have had very little known to, so it is possible that the code is incorrect and the build will not pass.

### CODE REVIEW

**Comment by COx2** [comment]
> I have identified two cases of memory leaks, and this is one of them. I will submit another proposal to fix the other one if it is identified.
I looked again at the above problem. I found that there was only one point in the change diff that was causing a memory leak.
Therefore, it would be helpful if you could confirm the operation and merge the change diff with this content.

**Comment by itoh-at-live2d-com** [comment]
@shiozawa-at-live2d-com 
Thank you for your contribution.
We will begin investigating this issue first.

**Comment by nakayasu-at-live2d-com** [comment]
@COx2 
I have reviewed the content here and would like to approve the PR, but it seems that only the OpenGL iOS has not been fixed, so please address that.

**Comment by nakayasu-at-live2d-com** [comment]
@COx2 
I have reviewed the content here.
I would like to approve the PR, but it seems that only OpenGL iOS is not fixed, so please fix it referring to this URL.
https://github.com/Live2D/CubismNativeSamples/blob/fix-memory-leak-opengl-ios/Samples/OpenGL/Demo/proj.ios.cmake/src/LAppLive2DManager.mm#L88-L89

I could not commit the fix there because it was protected by permissions.
I am sorry to trouble you, but I appreciate your support.

**Review by nakayasu-at-live2d-com — APPROVED** [review]

**Review by wada-at-live2d-com — APPROVED** [review]

**Review by wada-at-live2d-com — APPROVED** [review]

**Comment by wada-at-live2d-com** [comment]
This modification has been determined to be appropriate and will be merged.
Thank you for your modification.

**Pull request merged**
